### ISSUE TITLE
Could not find any valid controller serials

### ISSUE THREAD

**Issue by CRZTFR** [vanstinator/hass-raincloud#7]
Hi Vastinator, 

Just looking for some help on this issue, I appreciate your time. 

It looks like the integration is able to authenticate into the Melnor account happily, but seems to be having problems discovering controllers. 

Thanks in advance for your help. Cheers. 

> Logger: homeassistant.setup
Source: custom_components/raincloud/__init__.py:108
First occurred: 10:10:50 AM (1 occurrences)
Last logged: 10:10:50 AM

>Error during setup of component raincloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/raincloudy/helpers.py", line 63, in controller_serial_finder
    controllers_element = data.find(id="id_select_controller2").find_all(
AttributeError: 'NoneType' object has no attribute 'find_all'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/raincloud/__init__.py", line 108, in setup
    raincloud = RainCloudy(username=username, password=password)
  File "/usr/local/lib/python3.8/site-packages/raincloudy/core.py", line 63, in __init__
    self.login()
  File "/usr/local/lib/python3.8/site-packages/raincloudy/core.py", line 73, in login
    return self._authenticate
  File "/usr/local/lib/python3.8/site-packages/raincloudy/core.py", line 114, in _authenticate
    controller_serials = controller_serial_finder(self.html['setup'])
  File "/usr/local/lib/python3.8/site-packages/raincloudy/helpers.py", line 75, in controller_serial_finder
    raise RainCloudyException(
raincloudy.exceptions.RainCloudyException: Could not find any valid controller serials

**Comment by vanstinator** [comment]
/Are you still having trouble with this?
